# Generated by Django 6.0.7 on 2026-07-18 14:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('is_approved', models.BooleanField(default=False)),
                ('operating_hours', models.CharField(blank=True, max_length=200, null=True)),
                ('services', models.TextField(blank=True, help_text='e.g., Car Wash, Restaurant, ATM', null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_stations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gas Station',
                'verbose_name_plural': 'Gas Stations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QueueStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('green', '🟢 No Queue'), ('yellow', '🟡 Short Queue (5-10 min)'), ('red', '🔴 Long Queue (15+ min)')], default='green', max_length=10)),
                ('queue_length', models.IntegerField(default=0, help_text='Estimated number of cars waiting', validators=[django.core.validators.MinValueValidator(0)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_updates', to=settings.AUTH_USER_MODEL)),
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_status', to='stations.station')),
            ],
            options={
                'verbose_name': 'Queue Status',
                'verbose_name_plural': 'Queue Statuses',
            },
        ),
        migrations.CreateModel(
            name='FuelPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(choices=[('petrol_91', 'Petrol 91'), ('petrol_95', 'Petrol 95'), ('diesel', 'Diesel'), ('gas', 'CNG/LPG')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_prices', to='stations.station')),
            ],
            options={
                'verbose_name': 'Fuel Price',
                'verbose_name_plural': 'Fuel Prices',
                'ordering': ['station', 'fuel_type'],
                'unique_together': {('station', 'fuel_type')},
            },
        ),
    ]
