<<<<<<< HEAD
# Generated by Django 6.0.7 on 2026-07-21 12:29
=======
# Generated by Django 6.0.7 on 2026-07-20 13:05
>>>>>>> 4325fcac12587690b7aac25193aed142ef9c1976

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelprice',
            name='fuel_type',
<<<<<<< HEAD
            field=models.CharField(choices=[('banzen', 'Banzen'), ('gaz', 'Gaz')], max_length=20),
=======
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel')], max_length=20),
>>>>>>> 4325fcac12587690b7aac25193aed142ef9c1976
        ),
    ]
