# Generated by Django 6.0.7 on 2026-07-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelprice',
            name='fuel_type',
            field=models.CharField(choices=[('banzen', 'Banzen'), ('gaz', 'Gaz')], max_length=20),
        ),
    ]
