# Generated by Django 6.0.7 on 2026-07-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelprice',
            name='fuel_type',
            field=models.CharField(choices=[('banzen', 'Banzen'), ('gaz', 'Gaz')], max_length=20),
        ),
        migrations.AlterField(
            model_name='queuestatus',
            name='status',
            field=models.CharField(choices=[('green', 'No Queue'), ('yellow', 'Short Queue (5-10 min)'), ('red', 'Long Queue (15+ min)')], default='green', max_length=10),
        ),
    ]
