# Generated by Django 6.0.7 on 2026-07-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_alter_fuelprice_fuel_type_alter_queuestatus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='map_link',
            field=models.URLField(blank=True, help_text='Paste the Google Maps link for this station', max_length=500, null=True),
        ),
    ]
